version: '2'
services:
    appservices-app:
        image: appservices
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://appservices-mysql:3306/appservices?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    appservices-mysql:
        extends:
            file: mysql.yml
            service: appservices-mysql
